apiVersion: 1

deleteDatasources:
  - name: "Mimir"
  - name: "Alertmanager"
  - name: "Tempo"
  - name: "Loki"

datasources:
  - name: "Mimir"
    type: "prometheus"
    access: "proxy"
    orgId: 1
    url: "http://mimir:3300/prometheus"
    basicAuth: false
    isDefault: true
    version: 1
    editable: false
    uid: "mimir"
    jsonData:
      httpHeaderName1: "X-Scope-OrgID"
      alertmanagerUid: "alertmanager"
    secureJsonData:
      httpHeaderValue1: "fake"

  - name: "Alertmanager"
    type: "alertmanager"
    access: "proxy"
    orgId: 1
    url: "http://mimir:3300/alertmanager"
    basicAuth: false
    isDefault: false
    version: 1
    editable: false
    uid: "alertmanager"
    jsonData:
      httpHeaderName1: "X-Scope-OrgID"
      implementation: "prometheus"
    secureJsonData:
      httpHeaderValue1: "fake"

  - name: "Tempo"
    type: "tempo"
    access: "proxy"
    orgId: 1
    url: "http://tempo:3200"
    basicAuth: false
    isDefault: false
    version: 1
    editable: false
    apiVersion: 1
    uid: "tempo"
    jsonData:
      tracesToLogsV2:
        datasourceUid: "loki"
        spanStartTimeShift: "1h"
        spanEndTimeShift: "-1h"
        filterByTraceID: true
        filterBySpanID: true
        tags:
          - key: "service.name"
            value: "container"
      tracesToMetrics:
        datasourceUid: "mimir"
        spanStartTimeShift: "1h"
        spanEndTimeShift: "-1h"
      serviceMap:
        datasourceUid: "mimir"
      lokiSearch:
        datasourceUid: "loki"

  - name: "Loki"
    type: "loki"
    access: "proxy"
    orgId: 1
    url: "http://loki:3100"
    basicAuth: false
    isDefault: false
    version: 1
    editable: false
    apiVersion: 1
    uid: "loki"
    jsonData:
      derivedFields:
        - datasourceUid: "tempo"
          matcherRegex: '"(?:traceID|trace_id)":"(\w+)"'
          name: "trace_id"
          url: "$${__value.raw}"
