server:
  log_level: "warn"
  log_format: "json"

metrics:
  wal_directory: "/tmp/wal"
  wal_cleanup_age: "24h"
  wal_cleanup_period: "30m"
  global:
    scrape_interval: "15s"
    remote_write:
      - url: "http://mimir:3300/api/v1/push"
        headers:
          "X-Scope-OrgID": "fake"

logs:
  configs:
    - name: "loki"
      clients:
        - url: "http://loki:3100/loki/api/v1/push"
      positions:
        filename: "/tmp/positions.yaml"
      target_config:
        sync_period: "10s"
      scrape_configs:
        - job_name: "docker/system"
          docker_sd_configs:
            - host: "unix:///var/run/docker.sock"
              refresh_interval: "5s"
          relabel_configs:
            - action: "replace"
              replacement: "docker/system"
              source_labels:
                - "__meta_docker_container_id"
              target_label: "job"
            - source_labels:
                - "__meta_docker_container_name"
              regex: "/(.*)"
              target_label: "container"
            - source_labels:
                - "__meta_docker_container_log_stream"
              target_label: "stream"
        - job_name: "docker/services"
          static_configs:
            - targets:
                - "localhost"
              labels:
                job: "docker/services"
                __path__: "/var/lib/docker/containers/*/*log"
          pipeline_stages:
            - docker:
            - json:
                expressions:
                  level: "level"
                  span: "span"
                  timestamp: "timestamp"
                timestamp:
                  source: "timestamp"
                  format: "RFC3339Nano"
            - labels:
                level:
                span:

traces:
  configs:
    - name: "tempo"
      automatic_logging:
        backend: "logs_instance"
        logs_instance_name: "loki"
        spans: true
        roots: true
        processes: true
        process_attributes:
          - "span"
        span_attributes:
          - "span"
        labels:
          - "span"
        overrides:
          duration_key: "duration"
          trace_id_key: "trace_id"
      receivers:
        otlp:
          protocols:
            grpc:
              endpoint: "0.0.0.0:7021"
      remote_write:
        - endpoint: "tempo:4317"
          insecure: true

integrations:
  agent:
    enabled: true
  node_exporter:
    enabled: true
  cadvisor:
    enabled: true
    docker_only: true
