auth_enabled: false

server:
  http_listen_address: 0.0.0.0
  grpc_listen_address: 0.0.0.0
  http_listen_port: 3100
  grpc_listen_port: 9095
  log_level: "info"

common:
  storage:
    s3:
      endpoint: "minio:9000"
      insecure: true
      bucketnames: "loki"
      access_key_id: "accesskey"
      secret_access_key: "supersecret"
      s3forcepathstyle: true
  compactor_address: "http://loki:3100"

memberlist:
  dead_node_reclaim_time: "30s"
  gossip_to_dead_nodes_time: "15s"
  left_ingesters_timeout: "30s"
  gossip_interval: "2s"
  bind_port: 7946
  bind_addr:
    - "0.0.0.0"
  join_members:
    - "loki"

ingester:
  lifecycler:
    join_after: "10s"
    observe_period: "5s"
    ring:
      replication_factor: 1
      kvstore:
        store: "memberlist"
    final_sleep: "0s"
  chunk_idle_period: "1m"
  wal:
    enabled: true
    dir: "/loki/wal"
  max_chunk_age: "1m"
  chunk_retain_period: "30s"
  chunk_encoding: "snappy"
  chunk_target_size: 1.572864e+06
  chunk_block_size: 262144
  flush_op_timeout: "10s"

ruler:
  enable_api: true
  wal:
    dir: "/tmp/ruler-wal"
  storage:
    type: "local"
    local:
      directory: "/loki/rules"
  rule_path: "/tmp/prom-rules"
  remote_write:
    enabled: true
    clients:
      local:
        url: "http://prometheus:9090/api/v1/write"
        queue_config:
          capacity: 1
          batch_send_deadline: "0s"

schema_config:
  configs:
    - from: "2020-08-01"
      store: "boltdb-shipper"
      object_store: "s3"
      schema: "v11"
      index:
        prefix: "index_"
        period: "24h"

storage_config:
  boltdb_shipper:
    shared_store: "s3"
    active_index_directory: "/tmp/index"
    cache_location: "/tmp/boltdb-cache"

limits_config:
  max_cache_freshness_per_query: "10m"
  enforce_metric_name: false
  reject_old_samples: true
  reject_old_samples_max_age: "30m"
  split_queries_by_interval: "15m"
  ingestion_rate_mb: 10
  ingestion_burst_size_mb: 20

chunk_store_config:
  max_look_back_period: "336h"

table_manager:
  retention_deletes_enabled: true
  retention_period: "336h"

query_range:
  max_retries: 5
  align_queries_with_step: true
  parallelise_shardable_queries: true
  cache_results: true

frontend:
  log_queries_longer_than: "5s"
  compress_responses: true
  max_outstanding_per_tenant: 2048

query_scheduler:
  max_outstanding_requests_per_tenant: 1024

querier:
  query_ingesters_within: "2h"

compactor:
  working_directory: "/tmp/compactor"
  shared_store: "s3"
